name: ci

on:
  pull_request:
  push:

jobs:
  distcheck-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: pip-${{hashFiles('test/requirements*.txt')}}
      - run: env PYTESTFLAGS=--verbose test/macos-script.sh
